### ISSUE TITLE
Lighting bug

### ISSUE THREAD

**Issue by Hanse00** [Hanse00/CrafTech-old#12]
In the Alpha 1 release, lighting for the Blast Furnace is updated when the state changes (Furnace turns on or off), and on the first tile entity update.

This however means that on a dedicated server, any player that isn't loaded (and probably somewhat close), to the Blast Furnace on world load, won't get this update.

It's a relatively small problem, as the tile properly updates itself again when it's done burning the first items, never the less it's a bug.

**Comment by tterrag1098** [comment]
A simple once every few seconds lighting update wouldn't be horrible in terms of efficiency, but I'm sure there are smarter ways to do it.

**Comment by Hanse00** [comment]
I imagine you might be adding quite a load on to the server, if you're recalculating the lighting every few ticks for every instance of the tile entity in the world.

Though it might work, I'd rather find a more elegant solution to the problem.

I'm hoping to persuade @cloudhunter into giving me a hand :smile:

**Comment by tterrag1098** [comment]
True enough, I'm not sure then. Vanilla gets around this by using two separate IDs, but that would be silly. There must be some way to detect a chunk being loaded by a clientside player, but I have no idea what it is :P.

**Comment by Hanse00** [comment]
Me neither, but you've actually given me an idea what to look for, so thanks for that @tterrag1098 :P

**Comment by Hanse00** [comment]
@cloudhunter provided us with an (almost) working solution, any future discussion should go on over there, in pull request #19.
