### ISSUE TITLE
No crafting from coke block to item

### ISSUE THREAD

**Issue by Hanse00** [Hanse00/CrafTech-old#13]
I'm not sure if this is a bug, although I'm very inclined to think so.

The recipe for 9 coke items into a coke block looks like it should, but there doesn't seem to be a recipe for crafting a coke block back into the coke item.

While we're at it, I really think the coke block should have 9 times the burn time of a coke item, for the sake of consistency.

What's your take on this @yonsaber?

**Comment by yonsaber** [comment]
I can quickly add the reverse crafting recipe, I think I just forgot about adding it in the first place.
