### ISSUE TITLE
Crusher animation 

### ISSUE THREAD

**Issue by Hanse00** [Hanse00/CrafTech-old#22]
The crusher's animation is working optimally.

The problem is that all crusher blocks share the same animated texture, which just loops through it's images indefinitely.

For it to look proper, each crusher should be able to start it's animation, so that the animation always "starts" at the first frame, rather than just jumping into a texture that's always animating.

I believe doing this, will require using [tile entity special renderer](http://www.minecraftforge.net/wiki/Tile_entity_special_renderer).

**Comment by Hanse00** [comment]
How's the progress on this going @yonsaber?

**Comment by tterrag1098** [comment]
Honestly I would avoid using TESR at all costs, they are highly inefficient.

**Comment by Hanse00** [comment]
Do you know of any other possible ways of doing this? I don't.

From my reading it seems like that's how we have to do it.

**Comment by yonsaber** [comment]
Right after talking to @Hanse00 for a bit and having a play with TESR I working on a custom system. Its hacky but should work.

**Comment by Hanse00** [comment]
Closed as this feels like a waste of time for now, until the day my perfectionism gets the better of me, animations stay the way they are.
