### ISSUE TITLE
Power needed for crusher

### ISSUE THREAD

**Issue by yonsaber** [Hanse00/CrafTech-old#25]
The crusher should need power to run, we will need to set how much and change the process time based on the input power amount.

@Hanse00 which power type should we accept or shall we allow it to use any?

**Comment by Hanse00** [comment]
Any? Good luck on that one, implement 5 different APIs :P 

I say we use RF, grab the values used by the pulverizer, seems like a good place to start.

**Comment by yonsaber** [comment]
I will look into the TE API and start adding power.

**Comment by Hanse00** [comment]
TE is only updated to Minecraft 1.6.4 at the time though, and likely won't be done for 1.7 in a while, so I think the power need is something we need to hold off on for now, or go for the BuildCraft API.

**Comment by Hanse00** [comment]
I've actually been considering this a little over the past day, if we add power need, we're also adding a mod dependency.

This might not be such a huge thing, but in reality our mod right now is quite small, and stands alone completely. Maybe it's a wise choice for the time being to stay separated of any dependencies, and introduce them later, when it makes more sense.

If you agree with this @yonsaber, I think we should put power off for a later version, and polish the features we already have for v0.1 instead.

**Comment by yonsaber** [comment]
Agreed, makes things harder for us actually. I'll figure out something to make it need redstone power to work or something simple for now.

Lets revisit this later on.

**Comment by Hanse00** [comment]
Cool, closing for later review. :recycle:
