### ISSUE TITLE
Hot air pipes

### ISSUE THREAD

**Issue by yonsaber** [Hanse00/CrafTech-old#27]
Hot air pipes are needed for the blast furnace to run.

Thoughts on how this should be set up @Hanse00 ?

**Comment by Hanse00** [comment]
How about you come up with some thoughts of your own too?

I'm thinking a pipe similar to the TE itemducts, but for air.
We'll need some sort of thing to heat the air up in a place, could take RF and be some sort of engine, or just directly burn fuel.
Then the pipes can be used to transport the air, probably want some sort of way to isolate pipes for less heat loss, and make the pipes loose heat depending on the surroundings.

**Comment by yonsaber** [comment]
I didn't add any thing initially just wanted to hear your thoughts.
I was thinking maybe add a block that needs lava and generates hot air? Not infinite but runs for x amount of time.
Use TE pipes to transfer the air but either way works.

**Comment by Hanse00** [comment]
We could use liquid pipes and make air a fluid, that might work. But we wouldn't have the whole insulation and heat loss aspect.

Lava is definitely a way, but not the only way, generating heat with coal, wood, or other fuels should be doable too.

**Comment by Hanse00** [comment]
As this idea is something we won't be implementing any time soon (Not before the Blast Furnace is a multi block structure), I'm closing the issue for the time being.

Any collaborator should feel free to re-open this issue when it feels relevant to the state the project is in.
