### ISSUE TITLE
Multiblocks

### ISSUE THREAD

**Issue by yonsaber** [Hanse00/CrafTech-old#28]
Set the crusher and blast furnace to be multiblocks.

What are you thoughts about this @Hanse00 and how should we have them set up?

**Comment by Hanse00** [comment]
I'm not quite sure yet, this won't be any time soon.

I was thinking about a 5x5x15 shell of steel (we'll have to make that first), covered in bricks, I believe that's quite close to the construction of an actual blast furnace.

We'll also need pipe inputs for the hot air, a place to throw in the items to cook, and three outputs (pig iron, slag and ash).

This is definitely something we want to think through more closely, and come back to later.

FYI: You don't need to put my name everywhere, I get notified about everything anyone does in this repo :p

**Comment by yonsaber** [comment]
Agreed, multiblocks aren't going to be easy.

5x5x15 sounds very expensive but if it is close to the real construction I see that as only logical. Maybe we have blast furnace tiers e.g small furnace, runs slower but small construction etc then the full sized one.

There will be a lot to think about with this for sure, so more discussion is needed.

FYI: I know but just felt like tagging you :p

**Comment by Hanse00** [comment]
Well I've been looking around for some sources, blast furnaces seem to range from this:
![Alt text](http://upload.wikimedia.org/wikipedia/commons/6/6d/Blast_furnace_of_Govajdia.jpg)

To actual full on size factory plants, I don't think 5x5x15 is too big at all.
