### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Hanse00** [Hanse00/CrafTech-old#3]
It seems like a good idea to me that we open up the repo and make it public, much easier for people to chime in, much easier for us to have discussions with people.

But I'm thinking we should decide on how we actually want to license this work before we release it, what do you think @yonsaber?

I'm all for open source, maybe the LGPL license?

**Comment by yonsaber** [comment]
I am also happy for this to be open source.

LGPL license should be good, need to read up on it but what ever shall work best really.

**Comment by Hanse00** [comment]
We're going with GPL, done all the work for it.
