### ISSUE TITLE
Code standards

### ISSUE THREAD

**Issue by Hanse00** [Hanse00/CrafTech-old#32]
As we're nearing the first post-alpha release, I've been thinking a bit about the code.

As it is an open source project, and we also need to be able to maintain it in the long run, I think it'd be wise of us to set up some rules to write the code by.
Those rules could be something like:
- Add a comment before each method outlining the function of it
- Always place curly brackets on the same line as statement decleration
- Always declare global variables in the top of class
- Use ternary operators only when meaning is completely clear

I think we should add a wiki section for these rules, or add them to the readme, and then I'll run through the code as the last thing before 0.1 and make everything follow the standard.

**Comment by GUIpsp** [comment]
http://www.oracle.com/technetwork/java/codeconv-138413.html

**Comment by Hanse00** [comment]
I love you @GUIpsp <3

**Comment by Hanse00** [comment]
So after reading this over, it seems like exactly what we need.

The only addition I have to make is: Follow the vanilla Minecraft code as closely as possible, regarding package and class names.

**Comment by GUIpsp** [comment]
As another fun thing, the oracle standards usually come preconfigured in $IDE.

**Comment by Hanse00** [comment]
True, we just need to take care of writing the comments too.
