### ISSUE TITLE
Gradle improvements

### ISSUE THREAD

**Issue by Hanse00** [Hanse00/CrafTech-old#35]
I had a few ideas for improvements that I think we should do to the build script, I have no idea how to work with gradle, so if anyone feels like taking a stab at it, be my guest.

The enhancements are:
- Replace version number in `ModInfo.jar` - Currently only the mcmod.info gets replaced at build time)
- Allow for a dev flag - Basically I want to be able to run `gradle build --dev-build` or something similar, and get a jar that has `-DEV` appended to it's name.
- Take version number as build argument - I'd like to be able to run `gradle build --version 0.1` rather than have to replace the build number inside `build.gradle`.

**Comment by GUIpsp** [comment]
Paging @AbrarSyed.

**Comment by AbrarSyed** [comment]
Hmmm get on #forgegradle so we can talk, I'll be there in an hour.

**Comment by Hanse00** [comment]
@AbrarSyed I'll join you shortly, thanks for the offer to help.
