### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by Hanse00** [Hanse00/CrafTech-old#39]
It's been pointed out to me by @GUIpsp, that it'd be a very smart choice for us to change over to the [LGPL license](https://www.gnu.org/licenses/lgpl.html).

I'd just like to clear it with every contributor, so we don't have any silly issues down the line.

If @GUIpsp would care to explain why this is a necessary change for us (I don't remember the exact details), and @yonsaber and @Cloudhunter would just sign off on this change, that'd be great.

**Comment by yonsaber** [comment]
I am more than happy to change over the license. If it prevents issues in the future then it might be the best move!

**Comment by Cloudhunter** [comment]
Fine by me! LGPL is less restrictive and less viral - and means we don't have to add an exception for Minecraft code. Should also allow others to create addons for our mod with no need to be open source - I am a strong believer on not forcing others to be open source.
